# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Synthetic IDP responses used by the tests.

- PROJECTS: the live demo's project names (1 Oct 2026).
- SNEHA_FILE_CHECK: the IDP web app's own fixture (packages/frontend/src/components/FileCheckPanel/fixtures.ts).
- SNEHA_ELIGIBILITY: computed offline with the IDP's eligibility engine (packages/backend/app/eligibility.py)
  from handoff/seed-demo.py's inputs for Sneha (verified income 58,000).
All people, PANs and numbers are synthetic.
"""

PROJECTS = [
    {"project_id": "proj_DemoCalls_QaSample01", "name": "Telecaller QA \u2013 Sample calls", "status": "active", "description": "", "created_at": "2026-09-30T10:00:00Z"},
    {"project_id": "proj_DemoAmit_LoanFile01", "name": "Amit Patil \u2013 Personal Loan", "status": "active", "description": "", "created_at": "2026-09-30T10:00:00Z"},
    {"project_id": "proj_DemoRahul_LoanFile01", "name": "Rahul Deshmukh \u2013 Personal Loan", "status": "active", "description": "", "created_at": "2026-09-30T10:00:00Z"},
    {"project_id": "proj_DemoSneha_LoanFile01", "name": "Sneha Kulkarni \u2013 Personal Loan", "status": "active", "description": "", "created_at": "2026-09-30T10:00:00Z"},
]
QA_PROJECT_ID = "proj_DemoCalls_QaSample01"
SNEHA_PROJECT_ID = "proj_DemoSneha_LoanFile01"

SNEHA_FILE_CHECK = {'project_id': 'proj_DemoSneha_LoanFile01',
 'engine_version': '1.0',
 'as_of': '2026-09-28',
 'checklist': {'id': 'salaried_personal_loan', 'name': 'Personal Loan - Salaried'},
 'overall_verdict': 'NOT READY',
 'summary': '1 applicant: Sneha Anil Kulkarni NOT READY (5 issues)',
 'applicants': [{'applicant': 'Sneha Anil Kulkarni',
                 'pan': 'CKRPK7314M',
                 'verdict': 'NOT READY',
                 'reference_month': '2026-08',
                 'reference_month_label': 'Aug 2026',
                 'documents': [{'document_id': 's1',
                                'document_name': '01_loan_application_form.pdf',
                                'doc_type': 'loan_application'},
                               {'document_id': 's2',
                                'document_name': '02_identity_details_self_declaration.pdf',
                                'doc_type': 'identity_details'},
                               {'document_id': 's3',
                                'document_name': '03_salary_slip_2026-07_jul.pdf',
                                'doc_type': 'salary_slip'},
                               {'document_id': 's4',
                                'document_name': '04_salary_slip_2026-08_aug.pdf',
                                'doc_type': 'salary_slip'},
                               {'document_id': 's5',
                                'document_name': '05_bank_statement_2026-06_to_2026-08.pdf',
                                'doc_type': 'bank_statement'}],
                 'checklist': [{'item_id': 'loan_application',
                                'item': 'Loan application form',
                                'required': True,
                                'status': 'PRESENT',
                                'ok': True,
                                'detail': '01_loan_application_form.pdf',
                                'documents': ['01_loan_application_form.pdf']},
                               {'item_id': 'identity_details',
                                'item': 'Identity details (PAN + masked Aadhaar)',
                                'required': True,
                                'status': 'PRESENT',
                                'ok': True,
                                'detail': '02_identity_details_self_declaration.pdf',
                                'documents': ['02_identity_details_self_declaration.pdf']},
                               {'item_id': 'salary_slips',
                                'item': "Last 3 months' salary slips",
                                'required': True,
                                'status': 'MISSING',
                                'ok': False,
                                'detail': 'missing Jun 2026 slip(s); found: Jul 2026 '
                                          '(03_salary_slip_2026-07_jul.pdf), Aug 2026 '
                                          '(04_salary_slip_2026-08_aug.pdf)',
                                'documents': ['03_salary_slip_2026-07_jul.pdf',
                                              '04_salary_slip_2026-08_aug.pdf'],
                                'required_months': ['2026-06', '2026-07', '2026-08'],
                                'missing_months': ['2026-06']},
                               {'item_id': 'bank_statement',
                                'item': "Last 6 months' bank statement",
                                'required': True,
                                'status': 'MISSING',
                                'ok': False,
                                'detail': 'covers Jun 2026 – Aug 2026 '
                                          '(05_bank_statement_2026-06_to_2026-08.pdf); missing Mar 2026, Apr '
                                          '2026, May 2026',
                                'documents': ['05_bank_statement_2026-06_to_2026-08.pdf'],
                                'required_months': ['2026-03',
                                                    '2026-04',
                                                    '2026-05',
                                                    '2026-06',
                                                    '2026-07',
                                                    '2026-08'],
                                'missing_months': ['2026-03', '2026-04', '2026-05']},
                               {'item_id': 'form16_itr',
                                'item': 'Form-16 / ITR (latest FY)',
                                'required': True,
                                'status': 'MISSING',
                                'ok': False,
                                'detail': 'no Form-16 / ITR in the file',
                                'documents': []}],
                 'consistency': [{'check_id': 'pan',
                                  'check': 'PAN',
                                  'status': 'OK',
                                  'detail': 'CKRPK7314M on all 4 documents that carry a PAN',
                                  'documents': ['01_loan_application_form.pdf',
                                                '02_identity_details_self_declaration.pdf',
                                                '03_salary_slip_2026-07_jul.pdf',
                                                '04_salary_slip_2026-08_aug.pdf']},
                                 {'check_id': 'declared_vs_slip_net',
                                  'check': 'Declared net salary vs salary slips',
                                  'status': 'MISMATCH',
                                  'detail': 'declared ₹65,000 [01_loan_application_form.pdf] vs slip net '
                                            '₹58,000 – 12.1% apart; slip gross ₹65,000: gross appears '
                                            'declared as net',
                                  'documents': ['01_loan_application_form.pdf',
                                                '03_salary_slip_2026-07_jul.pdf',
                                                '04_salary_slip_2026-08_aug.pdf']},
                                 {'check_id': 'declared_vs_bank_credits',
                                  'check': 'Declared net salary vs bank credits',
                                  'status': 'MISMATCH',
                                  'detail': 'declared ₹65,000 vs bank salary credit ₹58,000 '
                                            '[05_bank_statement_2026-06_to_2026-08.pdf] – 12.1% apart',
                                  'documents': ['01_loan_application_form.pdf',
                                                '05_bank_statement_2026-06_to_2026-08.pdf']},
                                 {'check_id': 'slip_net_vs_bank_credits',
                                  'check': 'Salary slips vs bank credits',
                                  'status': 'OK',
                                  'detail': 'slip net ₹58,000 = bank credit ₹58,000',
                                  'documents': ['03_salary_slip_2026-07_jul.pdf',
                                                '05_bank_statement_2026-06_to_2026-08.pdf']}],
                 'income': {'declared_net': 65000,
                            'slip_net': 58000,
                            'slip_gross': 65000,
                            'bank_salary_credit': 58000,
                            'form16_gross': None,
                            'slip_gross_x12': 780000,
                            'bank_credits': []},
                 'reasons': [],
                 'missing_items': ['Salary slip: Jun 2026',
                                   'Bank statement: Mar 2026, Apr 2026, May 2026',
                                   'Form-16 / ITR (latest FY)'],
                 'mismatches': ['Declared net salary vs salary slips: declared ₹65,000 '
                                '[01_loan_application_form.pdf] vs slip net ₹58,000 – 12.1% apart; slip '
                                'gross ₹65,000: gross appears declared as net',
                                'Declared net salary vs bank credits: declared ₹65,000 vs bank salary credit '
                                '₹58,000 [05_bank_statement_2026-06_to_2026-08.pdf] – 12.1% apart'],
                 'needs_review': [],
                 'manual_review': []}],
 'pending_documents': [],
 'failed_documents': [],
 'no_facts_documents': [],
 'unsupported_documents': [],
 'unassigned_documents': []}

SNEHA_ELIGIBILITY = {'best_lender': 'Bajaj Finance',
 'best_lender_id': 'bajaj_finance',
 'best_lender_reason': 'lowest ROI among the lenders that cover ₹4,00,000',
 'income_considered': 58000.0,
 'obligations': 0.0,
 'requested': {'amount': 400000.0, 'tenure_months': 36},
 'sample': True,
 'label': 'indicative — the lender decides',
 'disclaimers': ['Indicative — the lender decides: the final eligibility, amount, ROI and tenure are the '
                 "lender's decision.",
                 'Sample policy — replace with your lender grid: the lender policies, pincode lists and '
                 "company categories used here are SAMPLE data, not any lender's real grid.",
                 'Calculated with fixed formulas in the backend (per-lakh EMI, FOIR and multiplier '
                 'eligibility, EMI as Excel PMT); no AI model decides any number.'],
 'applicant': 'Sneha Anil Kulkarni',
 'per_lender': [{'lender': 'HDFC Bank',
                 'lender_id': 'hdfc_bank',
                 'status': 'not_eligible',
                 'status_label': 'Not eligible',
                 'reasons': ["CIBIL score 712 is below HDFC Bank's minimum 750",
                             "6 enquiries in the last 90 days: more than HDFC Bank's limit of 4"],
                 'notes': [],
                 'eligible_amount': 0.0,
                 'emi': 0.0,
                 'tenure_months': 60,
                 'roi': 12.0},
                {'lender': 'ICICI Bank',
                 'lender_id': 'icici_bank',
                 'status': 'not_eligible',
                 'status_label': 'Not eligible',
                 'reasons': ["CIBIL score 712 is below ICICI Bank's minimum 725",
                             "6 enquiries in the last 90 days: more than ICICI Bank's limit of 5"],
                 'notes': [],
                 'eligible_amount': 0.0,
                 'emi': 0.0,
                 'tenure_months': 72,
                 'roi': 11.0},
                {'lender': 'Axis Bank',
                 'lender_id': 'axis_bank',
                 'status': 'not_eligible',
                 'status_label': 'Not eligible',
                 'reasons': ["CIBIL score 712 is below Axis Bank's minimum 750",
                             "6 enquiries in the last 90 days: more than Axis Bank's limit of 3"],
                 'notes': [],
                 'eligible_amount': 0.0,
                 'emi': 0.0,
                 'tenure_months': 60,
                 'roi': 11.5},
                {'lender': 'Bajaj Finance',
                 'lender_id': 'bajaj_finance',
                 'status': 'eligible',
                 'status_label': 'Eligible',
                 'reasons': [],
                 'notes': [],
                 'eligible_amount': 928000.0,
                 'emi': 17390.73,
                 'tenure_months': 84,
                 'roi': 14.0},
                {'lender': 'Tata Capital',
                 'lender_id': 'tata_capital',
                 'status': 'not_eligible',
                 'status_label': 'Not eligible',
                 'reasons': ["CIBIL score 712 is below Tata Capital's minimum 725",
                             "6 enquiries in the last 90 days: more than Tata Capital's limit of 4"],
                 'notes': [],
                 'eligible_amount': 0.0,
                 'emi': 0.0,
                 'tenure_months': 72,
                 'roi': 12.5}]}
